"""L3 kernel egress filter — nftables per-cgroup DROP rules (Phase 7, D7.1).

The pam_authnft pattern (LESSONS.md §1.5): a systemd transient scope pins
browser-child PIDs to a cgroup, and an nftables `socket cgroupv2` rule drops
private/link-local/metadata egress for sockets inside that cgroup. No suid
binary, no kernel module, works for ad-hoc processes.

Why a kernel layer at all? The browser children outlive our process and make
their own sockets — a userspace floor (egress.py) sees the URLs *we* hand
them, but only the kernel sees every socket they open. L1 + L2 + L3 are the
complete containment envelope; each layer catches what the others can't.

Enforcement (D7.1, locked): browser-tier ops REFUSE to launch without the
filter installed when `SEARCH_GATEWAY_HARDEN=required` (the default).
`permissive` is the explicit opt-out for sandboxed CI that cannot run nft.
The service-level floor (systemd IPAddressDeny) keeps loopback open for
Redis/SearXNG; browser children are scoped (systemd-run --scope) so the
strict cgroup rules apply to *them* — never to the gateway's own loopback
deps.

No kernel is touched by the test suite: `build_rules` is a pure function
(golden-tested), `status`/`install` probe nft through mocked subprocesses.
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import shutil
import subprocess
import time
from pathlib import Path

from ..config import HARDEN, HARDEN_SUDO

logger = logging.getLogger("search_gateway.extract.harden")

NFT_TABLE = "inet sg_egress"
STATE_PATH = Path(os.path.expanduser("~/.config/search-gateway/harden.json"))

# Everything the floor blocks, expressed for the kernel. No exemptions here —
# this is the absolute egress floor for scoped browser children.
_PRIVATE_V4 = (
    "127.0.0.0/8",      # loopback
    "10.0.0.0/8",       # RFC1918
    "172.16.0.0/12",    # RFC1918
    "192.168.0.0/16",   # RFC1918
    "169.254.0.0/16",   # link-local + IMDS
    "100.64.0.0/10",    # CGNAT + Alibaba IMDS
    "0.0.0.0/8",        # "this network"
)
_PRIVATE_V6 = (
    "::1/128",          # loopback
    "fe80::/10",        # link-local
    "::/128",           # unspecified
    "fd00:ec2::254/128",  # Azure IMDS v6
)

# `socket cgroupv2 level N "path"`: matches sockets whose process cgroup path
# (relative to the cgroup2 root) has the given `N` components and equals
# `path`. N = component count, derived below — deterministic, golden-tested.
_CGROUP_HEADER = "socket cgroupv2 level {level} \"{path}\" goto block_private"


class EgressUnhardened(Exception):
    """Browser-tier op refused: the kernel filter is not installed.

    Message is the load-bearing contract with the envelope
    (`blocked (egress-unhardened): …`) — keep the prefix stable.
    """

    def __init__(self):
        super().__init__(
            "blocked (egress-unhardened): run 'search-gateway harden "
            "--install --sudo'")


def _component_count(cgroup_path: str) -> int:
    """Number of cgroup path components after the leading '/'.

    `/user.slice/user-1000.slice/session-1.scope` -> 3
    """
    return len([c for c in cgroup_path.strip("/").split("/") if c])


def build_rules(cgroup_path: str) -> str:
    """The nft script (pure function, golden-tested).

    `cgroup_path` is the cgroup2-relative path of the scope that will contain
    the browser children (e.g. `/user.slice/user-1000.slice/sg-egress-42.scope`).
    """
    level = _component_count(cgroup_path)
    rel = cgroup_path.strip("/")
    lines = [
        "# Generated by search-gateway harden --install (v0.4.2). Do not edit by hand.",
        f"table {NFT_TABLE} {{",
        "\tchain output {",
        "\t\ttype filter hook output priority filter; policy accept;",
        f"\t\t{_CGROUP_HEADER.format(level=level, path=rel)}",
        "\t\taccept",
        "\t}",
        "",
        "\tchain block_private {",
    ]
    for net in _PRIVATE_V4:
        lines.append(f"\t\tip daddr {net} drop")
    for net in _PRIVATE_V6:
        lines.append(f"\t\tip6 daddr {net} drop")
    lines += [
        "\t\taccept",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def _nft() -> str | None:
    return shutil.which("nft")


def cgroupv2_mounted() -> bool:
    try:
        ctrl = Path("/sys/fs/cgroup/cgroup.controllers")
        return ctrl.is_file()
    except OSError:
        return False


def current_cgroup() -> str | None:
    """cgroup2-relative path of the current process, or None."""
    try:
        for line in Path("/proc/self/cgroup").read_text(encoding="utf-8").splitlines():
            if line.startswith("0::"):
                return line[3:]
    except OSError:
        pass
    return None


def _run_nft(args: list[str]) -> tuple[int, str]:
    """Probe nft (mocked in tests; never crashes)."""
    binary = _nft()
    if binary is None:
        return 127, "nft not found"
    try:
        r = subprocess.run(  # noqa: S603 — operator-triggered hardening probe
            [binary, *args], capture_output=True, text=True, timeout=10)
        return r.returncode, (r.stdout or r.stderr or "").strip()
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 1, str(exc)


def _load_state() -> dict:
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _save_state(state: dict) -> None:
    try:
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")
    except OSError as exc:
        logger.warning("harden: cannot write state file: %s", exc)


def table_installed() -> bool:
    """Is the sg_egress table live in the kernel? (authoritative probe)."""
    code, _ = _run_nft(["list", "table", *NFT_TABLE.split()])
    return code == 0


def systemd_run_available() -> bool:
    return shutil.which("systemd-run") is not None


def status() -> dict:
    """Read-only state: mode, install status, scoping availability, coverage."""
    installed = table_installed()
    nft_ok = _nft() is not None
    cg = current_cgroup()
    state = _load_state()
    covered = bool(installed and cg and state.get("cgroup_path")
                   and cg.rstrip("/") == state["cgroup_path"].rstrip("/"))
    mode = "required" if HARDEN == "required" else "permissive"
    problems: list[str] = []
    if not nft_ok:
        problems.append("nft not on PATH")
    if not cgroupv2_mounted():
        problems.append("cgroupv2 not mounted")
    if not systemd_run_available():
        problems.append("systemd-run not available (needed to scope browser children)")
    if installed and state.get("cgroup_path") and not covered:
        problems.append(
            f"current cgroup {cg or '?'} is not the scoped "
            f"{state.get('cgroup_path')} — browser children would be unscoped")
    return {
        "mode": mode,
        "installed": installed,
        "nft": nft_ok,
        "cgroupv2": cgroupv2_mounted(),
        "systemd_run": systemd_run_available(),
        "covered": covered,
        "cgroup_path": state.get("cgroup_path"),
        "problems": problems,
    }


def enforce(require_coverage: bool = False) -> None:
    """D7.1 gate: raise EgressUnhardened unless the filter is live and
    scoping is possible. No-op in permissive mode (explicit opt-out).

    `require_coverage=True` (Camoufox): the *gateway process itself* must sit
    inside the scoped cgroup — Camoufox spawns its own children and cannot be
    wrapped, so coverage is mandatory. For opencli ops the child is wrapped
    in a transient scope instead (`run_opencli`), so coverage is optional.
    """
    if HARDEN != "required":
        return
    if not table_installed():
        raise EgressUnhardened()
    if not systemd_run_available():
        raise EgressUnhardened()
    if require_coverage:
        state = _load_state()
        cg = current_cgroup()
        if not (cg and state.get("cgroup_path")
                and cg.rstrip("/") == state["cgroup_path"].rstrip("/")):
            raise EgressUnhardened()


def install(*, sudo: bool = False, dry_run: bool = False) -> dict:
    """Idempotent install: derive the scope cgroup from the current process,
    write the nft ruleset, load it, save state. Refuses (reports, never
    crashes) when nft or cgroupv2 is absent. `--sudo` runs the nft load with
    elevation; without sudo, the ruleset is written to a file for the
    operator to load (`nft -f`), and state marks it pending."""
    if _nft() is None:
        return {"ok": False, "error": "nft not on PATH — cannot harden"}
    if not cgroupv2_mounted():
        return {"ok": False, "error": "cgroupv2 not mounted at /sys/fs/cgroup"}
    cg = current_cgroup()
    if not cg:
        return {"ok": False, "error": "cannot read /proc/self/cgroup"}
    rules = build_rules(cg)
    if dry_run:
        return {"ok": True, "dry_run": True, "cgroup_path": cg, "rules": rules}
    rules_path = Path(os.path.expanduser("~/.config/search-gateway/sg-egress.nft"))
    try:
        rules_path.parent.mkdir(parents=True, exist_ok=True)
        rules_path.write_text(rules, encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "error": f"cannot write rules file: {exc}"}
    if sudo or HARDEN_SUDO or os.geteuid() == 0:
        code, err = _run_nft(["-f", str(rules_path)])
        if code != 0:
            return {"ok": False, "error": f"nft -f failed: {err or code}"}
    else:
        logger.info("harden: rules written to %s — load with 'sudo nft -f %s'",
                    rules_path, rules_path)
        _save_state({"cgroup_path": cg, "installed_at": int(time.time()),
                     "pending_load": str(rules_path)})
        return {"ok": True, "pending_load": str(rules_path),
                "cgroup_path": cg,
                "note": "rules written; load with 'sudo nft -f' or re-run with --sudo"}
    _save_state({"cgroup_path": cg, "installed_at": int(time.time())})
    return {"ok": True, "cgroup_path": cg, "rules_file": str(rules_path)}


def uninstall() -> dict:
    code, err = _run_nft(["delete", "table", *NFT_TABLE.split()])
    if code == 0:
        with contextlib.suppress(OSError):
            STATE_PATH.unlink()
        return {"ok": True}
    return {"ok": False, "error": f"nft delete failed: {err or code}"}
