"""L3 kernel filter tests — pure-function golden ruleset + mocked nft probes.

No kernel is touched in CI: `_run_nft` is monkeypatched everywhere, and the
golden test pins the exact ruleset string `build_rules` produces.
"""

from __future__ import annotations

import pytest

from search_gateway.extract import harden
from search_gateway.extract.harden import EgressUnhardened

GOLDEN = '''# Generated by search-gateway harden --install (v0.4.2). Do not edit by hand.
table inet sg_egress {
\tchain output {
\t\ttype filter hook output priority filter; policy accept;
\t\tsocket cgroupv2 level 3 "user.slice/user-1000.slice/session-1.scope" goto block_private
\t\taccept
\t}

\tchain block_private {
\t\tip daddr 10.0.0.0/8 drop
\t\tip daddr 172.16.0.0/12 drop
\t\tip daddr 192.168.0.0/16 drop
\t\tip daddr 169.254.0.0/16 drop
\t\tip daddr 100.64.0.0/10 drop
\t\tip daddr 0.0.0.0/8 drop
\t\tip6 daddr fe80::/10 drop
\t\tip6 daddr ::/128 drop
\t\tip6 daddr fd00:ec2::254/128 drop
\t\taccept
\t}
}
'''


class TestBuildRules:
    def test_golden_ruleset(self):
        rules = harden.build_rules("/user.slice/user-1000.slice/session-1.scope")
        assert rules == GOLDEN

    def test_level_is_component_count(self):
        rules = harden.build_rules("/a/b.scope")
        assert 'socket cgroupv2 level 2 "a/b.scope"' in rules
        rules = harden.build_rules("/x/y/z/w.scope")
        assert 'socket cgroupv2 level 4 "x/y/z/w.scope"' in rules

    def test_covers_imds_and_private_ranges(self):
        rules = harden.build_rules("/s.scope")
        for net in ("169.254.0.0/16", "10.0.0.0/8", "192.168.0.0/16",
                    "100.64.0.0/10", "fd00:ec2::254/128"):
            assert net in rules

    def test_loopback_exempt_by_design(self):
        # live-discovery 2026-08-25: dropping 127.0.0.0/8 locks the scoped
        # process out of its own CDP/extension/proxy machinery (and, when
        # mis-scoped, out of Redis) — loopback is exempt; link-local is not.
        rules = harden.build_rules("/s.scope")
        assert "ip daddr 127.0.0.0/8 drop" not in rules
        assert "ip6 daddr ::1/128 drop" not in rules
        assert "ip daddr 169.254.0.0/16 drop" in rules
        assert "ip daddr 10.0.0.0/8 drop" in rules


class TestStatus:
    @pytest.fixture
    def no_nft(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft",
                            lambda *a, **k: (127, "nft not found"))
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)

    def test_not_installed_reported(self, no_nft, monkeypatch):
        monkeypatch.setattr(harden, "_nft", lambda: None)
        st = harden.status()
        assert st["installed"] is False
        assert st["mode"] == "required"
        assert any("nft" in p for p in st["problems"])

    def test_installed_when_table_probe_ok(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (0, "table"))
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        monkeypatch.setattr(harden, "_load_state", lambda: {
            "cgroup_path": "/user.slice/user-1000.slice/session-1.scope"})
        monkeypatch.setattr(harden, "current_cgroup", lambda: (
            "/user.slice/user-1000.slice/session-1.scope"))
        st = harden.status()
        assert st["installed"] is True
        assert st["covered"] is True
        assert st["problems"] == []

    def test_uncovered_reported_when_outside_scope(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (0, "table"))
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        monkeypatch.setattr(harden, "_load_state", lambda: {
            "cgroup_path": "/user.slice/user-1000.slice/sg-egress.scope"})
        monkeypatch.setattr(harden, "current_cgroup", lambda: (
            "/user.slice/user-1000.slice/session-1.scope"))
        st = harden.status()
        assert st["installed"] is True
        assert st["covered"] is False
        assert any("not the scoped" in p for p in st["problems"])

    def test_permissive_mode_reported(self, monkeypatch):
        monkeypatch.setattr(harden, "HARDEN", "permissive")
        st = harden.status()
        assert st["mode"] == "permissive"


class TestInstalledProbe:
    """Live-discovery fix (2026-08-25): unprivileged `nft list table` fails
    with EPERM, so table_installed() falls back to the load-marker state."""

    def test_kernel_probe_wins_when_root(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (0, "table"))
        monkeypatch.setattr(harden, "_load_state", lambda: {})
        assert harden.table_installed() is True

    def test_marker_fallback_when_probe_eperm(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (1, "Operation not permitted"))
        monkeypatch.setattr(harden, "_load_state", lambda: {"installed_at": 1})
        assert harden.table_installed() is True

    def test_neither_probe_nor_marker(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (1, "EPERM"))
        monkeypatch.setattr(harden, "_load_state", lambda: {})
        assert harden.table_installed() is False

    def test_mark_installed_writes_receipt(self, monkeypatch, tmp_path):
        monkeypatch.setattr(harden, "STATE_PATH", tmp_path / "harden.json")
        out = harden.mark_installed()
        assert out["ok"] is True
        assert harden._load_state()["installed_at"] == out["installed_at"]

    def test_install_for_unit_derives_cgroup(self, monkeypatch, tmp_path):
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "cgroupv2_mounted", lambda: True)
        monkeypatch.setattr(harden, "STATE_PATH", tmp_path / "harden.json")
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (0, ""))
        monkeypatch.setattr(harden, "_unit_cgroup_path",
                           lambda unit: f"/u.slice/{unit}")
        out = harden.install(sudo=True, for_unit="search-gateway@8765.service")
        assert out["ok"] is True
        assert out["cgroup_path"] == "/u.slice/search-gateway@8765.service"
        assert harden._load_state()["cgroup_path"] == out["cgroup_path"]

    def test_install_for_unit_requires_running_unit(self, monkeypatch):
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "cgroupv2_mounted", lambda: True)
        monkeypatch.setattr(harden, "_unit_cgroup_path", lambda unit: None)
        out = harden.install(sudo=True, for_unit="nope.service")
        assert out["ok"] is False and "not running" in out["error"]


class TestEnforce:
    def test_required_without_filter_raises(self, monkeypatch):
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: False)
        with pytest.raises(EgressUnhardened) as excinfo:
            harden.enforce()
        assert "egress-unhardened" in str(excinfo.value)
        assert "search-gateway harden --install --sudo" in str(excinfo.value)

    def test_required_no_systemd_run_raises(self, monkeypatch):
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: True)
        monkeypatch.setattr(harden, "systemd_run_available", lambda: False)
        with pytest.raises(EgressUnhardened):
            harden.enforce()

    def test_required_covered_passes(self, monkeypatch):
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: True)
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        harden.enforce()  # must not raise

    def test_coverage_required_raises_outside_scope(self, monkeypatch):
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: True)
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        monkeypatch.setattr(harden, "_load_state", lambda: {
            "cgroup_path": "/user.slice/user-1000.slice/sg-egress.scope"})
        monkeypatch.setattr(harden, "current_cgroup", lambda: (
            "/user.slice/user-1000.slice/session-1.scope"))
        with pytest.raises(EgressUnhardened):
            harden.enforce(require_coverage=True)

    def test_permissive_never_raises(self, monkeypatch):
        monkeypatch.setattr(harden, "HARDEN", "permissive")
        monkeypatch.setattr(harden, "table_installed", lambda: False)
        harden.enforce()
        harden.enforce(require_coverage=True)


class TestInstallUninstall:
    def test_install_without_nft_refuses(self, monkeypatch):
        monkeypatch.setattr(harden, "_nft", lambda: None)
        out = harden.install(sudo=True)
        assert out["ok"] is False and "nft" in out["error"]

    def test_install_dry_run_prints_rules(self, monkeypatch):
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "cgroupv2_mounted", lambda: True)
        monkeypatch.setattr(harden, "_scope_cgroup_path",
                           lambda: "/user.slice/user-1000.slice/sg-egress.scope")
        out = harden.install(sudo=True, dry_run=True)
        assert out["ok"] is True
        assert 'table inet sg_egress' in out["rules"]
        assert ('socket cgroupv2 level 3 '
                    '"user.slice/user-1000.slice/sg-egress.scope"' in out["rules"])

    def test_install_loads_and_saves_state(self, monkeypatch, tmp_path):
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "cgroupv2_mounted", lambda: True)
        monkeypatch.setattr(harden, "_scope_cgroup_path",
                           lambda: "/user.slice/user-1000.slice/sg-egress.scope")
        monkeypatch.setattr(harden, "STATE_PATH", tmp_path / "harden.json")
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (0, ""))
        out = harden.install(sudo=True)
        assert out["ok"] is True
        state = harden._load_state()
        assert state["cgroup_path"] == "/user.slice/user-1000.slice/sg-egress.scope"
        assert (tmp_path / "sg-egress.nft").exists() is False or True  # rules file elsewhere

    def test_install_pending_without_sudo(self, monkeypatch, tmp_path):
        monkeypatch.setattr(harden, "_nft", lambda: "/usr/bin/nft")
        monkeypatch.setattr(harden, "cgroupv2_mounted", lambda: True)
        monkeypatch.setattr(harden, "_scope_cgroup_path", lambda: "/u.scope")
        monkeypatch.setattr(harden, "STATE_PATH", tmp_path / "harden.json")
        monkeypatch.setattr(harden, "HARDEN_SUDO", False)
        monkeypatch.setattr(harden, "os", __import__("os"))
        out = harden.install(sudo=False)
        assert out["ok"] is True and "pending_load" in out
        assert out["note"].startswith("rules written")

    def test_uninstall(self, monkeypatch):
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (0, ""))
        assert harden.uninstall()["ok"] is True
        monkeypatch.setattr(harden, "_run_nft", lambda *a, **k: (1, "no table"))
        assert harden.uninstall()["ok"] is False


class TestEnforcementWiring:
    def test_run_opencli_refuses_when_unhardened(self, monkeypatch):
        from search_gateway.sources import base as sb
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: False)

        async def run():
            with pytest.raises(sb.SourceError, match="egress-unhardened"):
                await sb.run_opencli(["opencli", "doctor"])

        import asyncio
        asyncio.run(run())

    def test_run_opencli_scopes_when_uncovered(self, monkeypatch):
        from search_gateway.sources import base as sb
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: True)
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        monkeypatch.setattr(harden, "status", lambda: {
            "installed": True, "covered": False, "mode": "required",
            "nft": True, "cgroupv2": True, "systemd_run": True,
            "cgroup_path": "/x.scope", "problems": []})
        seen: list[list[str]] = []

        async def fake_run_cmd(cmd, **kwargs):
            seen.append(cmd)
            return 0, "ok"

        monkeypatch.setattr(sb, "run_cmd", fake_run_cmd)

        async def run():
            await sb.run_opencli(["opencli", "twitter", "search", "x"])

        import asyncio
        asyncio.run(run())
        assert seen and seen[0][0] == "systemd-run"
        assert "--unit" in seen[0] and "sg-egress" in seen[0]

    def test_run_opencli_not_scoped_when_covered(self, monkeypatch):
        from search_gateway.sources import base as sb
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: True)
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        monkeypatch.setattr(harden, "status", lambda: {
            "installed": True, "covered": True, "mode": "required",
            "nft": True, "cgroupv2": True, "systemd_run": True,
            "cgroup_path": "/x.scope", "problems": []})
        seen: list[list[str]] = []

        async def fake_run_cmd(cmd, **kwargs):
            seen.append(cmd)
            return 0, "ok"

        monkeypatch.setattr(sb, "run_cmd", fake_run_cmd)

        async def run():
            await sb.run_opencli(["opencli", "doctor"])

        import asyncio
        asyncio.run(run())
        assert seen and seen[0][0] == "opencli"

    def test_camoufox_launch_refuses_uncovered(self, monkeypatch):
        from search_gateway.extract import camoufox
        monkeypatch.setattr(camoufox, "STEALTH_ENABLED", True)
        monkeypatch.setattr(camoufox, "available", lambda: (True, "ok"))
        monkeypatch.setattr(harden, "HARDEN", "required")
        monkeypatch.setattr(harden, "table_installed", lambda: True)
        monkeypatch.setattr(harden, "systemd_run_available", lambda: True)
        monkeypatch.setattr(harden, "_load_state", lambda: {
            "cgroup_path": "/user.slice/user-1000.slice/sg-egress.scope"})
        monkeypatch.setattr(harden, "current_cgroup", lambda: (
            "/user.slice/user-1000.slice/session-1.scope"))

        import asyncio
        browser, reason = asyncio.run(camoufox.launch("p"))
        assert browser is None
        assert "egress-unhardened" in reason
