"""L3 kernel egress filter — nftables per-cgroup DROP rules (Phase 7, D7.1).

The pam_authnft pattern (LESSONS.md §1.5): a systemd transient scope pins
browser-child PIDs to a cgroup, and an nftables `socket cgroupv2` rule drops
private/link-local/metadata egress for sockets inside that cgroup. No suid
binary, no kernel module, works for ad-hoc processes.

Why a kernel layer at all? The browser children outlive our process and make
their own sockets — a userspace floor (egress.py) sees the URLs *we* hand
them, but only the kernel sees every socket they open. L1 + L2 + L3 are the
complete containment envelope; each layer catches what the others can't.

Enforcement (D7.1, locked): browser-tier ops REFUSE to launch without the
filter installed when `KORTEX_SEARCH_HARDEN=required` (the default).
`permissive` is the explicit opt-out for sandboxed CI that cannot run nft.
The service-level floor (systemd IPAddressDeny) keeps loopback open for
Redis/SearXNG; browser children are scoped (systemd-run --scope) so the
strict cgroup rules apply to *them* — never to the gateway's own loopback
deps.

No kernel is touched by the test suite: `build_rules` is a pure function
(golden-tested), `status`/`install` probe nft through mocked subprocesses.
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import shutil
import subprocess
import time
from pathlib import Path

from ..config import HARDEN, HARDEN_SUDO

logger = logging.getLogger("kortex_search.extract.harden")

NFT_TABLE = "inet ks_egress"
STATE_PATH = Path(os.path.expanduser("~/.config/kortex-search/harden.json"))
RULES_PATH = Path(os.path.expanduser("~/.config/kortex-search/ks-egress.nft"))
# The ruleset the ROOT loader unit applies (sweep 2026-08-31). RULES_PATH
# above is the user-side GENERATION artifact only — it must never sit in a
# root load path: a NOPASSWD `nft -f <user-writable-file>` grant is an
# escalation seam (any kbj-uid process — including the browser automation —
# can rewrite the file and have root parse it into the nf_tables kernel
# surface). The root-owned copy lives outside the home dir; the loader is a
# root systemd unit that validates (nft -c) then applies. No sudoers entry.
SYSTEM_RULES_PATH = Path("/etc/kortex-search/ks-egress.nft")

# Everything the floor blocks, expressed for the kernel. No exemptions here —
# this is the absolute egress floor for scoped browser children.
#
# LOOPBACK IS EXEMPT BY DESIGN (live-discovery 2026-08-25): the browser's own
# machinery lives on 127.0.0.1 — opencli's CDP bridge, the extension
# websocket, and the L2 egress proxy. Dropping loopback locks the scoped
# process out of its own stack (and, in a mis-scoped deploy, out of Redis —
# observed). Compensating controls: Redis is password-protected, the L1 floor
# gates URLs pre-nav/post-redirect, and the L2 forced-proxy routes the
# browser's external egress. What the kernel floor still absolutely blocks:
# link-local/IMDS (169.254.0.0/16 etc.), RFC1918, CGNAT, v6 equivalents.
_PRIVATE_V4 = (
    "10.0.0.0/8",       # RFC1918
    "172.16.0.0/12",    # RFC1918
    "192.168.0.0/16",   # RFC1918
    "169.254.0.0/16",   # link-local + IMDS
    "100.64.0.0/10",    # CGNAT + Alibaba IMDS
    "0.0.0.0/8",        # "this network"
)
_PRIVATE_V6 = (
    "fe80::/10",        # link-local
    "::/128",           # unspecified
    "fd00:ec2::254/128",  # Azure IMDS v6
)

# `socket cgroupv2 level N "path"`: matches sockets whose process cgroup path
# (relative to the cgroup2 root) has the given `N` components and equals
# `path`. N = component count, derived below — deterministic, golden-tested.
_CGROUP_HEADER = "socket cgroupv2 level {level} \"{path}\" goto block_private"


class EgressUnhardened(Exception):
    """Browser-tier op refused: the kernel filter is not installed.

    Message is the load-bearing contract with the envelope
    (`blocked (egress-unhardened): …`) — keep the prefix stable.
    """

    def __init__(self):
        super().__init__(
            "blocked (egress-unhardened): run 'kortex-search harden "
            "--install --sudo'")


def _component_count(cgroup_path: str) -> int:
    """Number of cgroup path components after the leading '/'.

    `/user.slice/user-1000.slice/session-1.scope` -> 3
    """
    return len([c for c in cgroup_path.strip("/").split("/") if c])


def build_rules(cgroup_path: str) -> str:
    """The nft script (pure function, golden-tested).

    `cgroup_path` is the cgroup2-relative path of the scope that will contain
    the browser children (e.g. `/user.slice/user-1000.slice/ks-egress-42.scope`).
    """
    level = _component_count(cgroup_path)
    rel = cgroup_path.strip("/")
    lines = [
        "# Generated by kortex-search harden --install (v0.5.0). Do not edit by hand.",
        f"table {NFT_TABLE} {{",
        "\tchain output {",
        "\t\ttype filter hook output priority filter; policy accept;",
        f"\t\t{_CGROUP_HEADER.format(level=level, path=rel)}",
        "\t\taccept",
        "\t}",
        "",
        "\tchain block_private {",
    ]
    for net in _PRIVATE_V4:
        lines.append(f"\t\tip daddr {net} drop")
    for net in _PRIVATE_V6:
        lines.append(f"\t\tip6 daddr {net} drop")
    lines += [
        "\t\taccept",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def _nft() -> str | None:
    return shutil.which("nft")


def cgroupv2_mounted() -> bool:
    try:
        ctrl = Path("/sys/fs/cgroup/cgroup.controllers")
        return ctrl.is_file()
    except OSError:
        return False


def current_cgroup() -> str | None:
    """cgroup2-relative path of the current process, or None."""
    try:
        for line in Path("/proc/self/cgroup").read_text(encoding="utf-8").splitlines():
            if line.startswith("0::"):
                return line[3:]
    except OSError:
        pass
    return None


def _run_nft(args: list[str]) -> tuple[int, str]:
    """Probe nft (mocked in tests; never crashes)."""
    binary = _nft()
    if binary is None:
        return 127, "nft not found"
    try:
        r = subprocess.run(  # noqa: S603 — operator-triggered hardening probe
            [binary, *args], capture_output=True, text=True, timeout=10)
        return r.returncode, (r.stdout or r.stderr or "").strip()
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 1, str(exc)


def _load_state() -> dict:
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _save_state(state: dict) -> None:
    try:
        STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        STATE_PATH.write_text(json.dumps(state, indent=2), encoding="utf-8")
    except OSError as exc:
        logger.warning("harden: cannot write state file: %s", exc)


def table_installed() -> bool:
    """Is the ks_egress table live? (authoritative where possible).

    Probing order (live-discovery 2026-08-25 — unprivileged `nft list table`
    fails with EPERM, so the kernel probe only works as root):
      1. direct `nft list table` — root/system contexts;
      2. the installed-at state marker — written by the privileged load path
         (`install --sudo` or `harden --mark-installed` after a successful
         `sudo nft -f`); `nft -f` both validates and applies, so a successful
         load is kernel-verified at load time.
    """
    code, _ = _run_nft(["list", "table", *NFT_TABLE.split()])
    if code == 0:
        return True
    state = _load_state()
    return bool(state.get("installed_at"))


def mark_installed() -> dict:
    """Record a successful privileged load (ran after `sudo nft -f`).

    The unprivileged gateway cannot probe the kernel table (EPERM); the
    loader's success is the verification — this marker is its receipt.
    """
    state = _load_state()
    state["installed_at"] = int(time.time())
    _save_state(state)
    return {"ok": True, "installed_at": state["installed_at"]}


def systemd_run_available() -> bool:
    return shutil.which("systemd-run") is not None


def status() -> dict:
    """Read-only state: mode, install status, scoping availability, coverage."""
    installed = table_installed()
    nft_ok = _nft() is not None
    cg = current_cgroup()
    state = _load_state()
    covered = bool(installed and cg and state.get("cgroup_path")
                   and cg.rstrip("/") == state["cgroup_path"].rstrip("/"))
    mode = "required" if HARDEN == "required" else "permissive"
    problems: list[str] = []
    if not nft_ok:
        problems.append("nft not on PATH")
    if not cgroupv2_mounted():
        problems.append("cgroupv2 not mounted")
    if not systemd_run_available():
        problems.append("systemd-run not available (needed to scope browser children)")
    if installed and state.get("cgroup_path") and not covered:
        problems.append(
            f"current cgroup {cg or '?'} is not the scoped "
            f"{state.get('cgroup_path')} — browser children would be unscoped")
    return {
        "mode": mode,
        "installed": installed,
        "nft": nft_ok,
        "cgroupv2": cgroupv2_mounted(),
        "systemd_run": systemd_run_available(),
        "covered": covered,
        "cgroup_path": state.get("cgroup_path"),
        "system_rules": SYSTEM_RULES_PATH.exists(),
        "problems": problems,
    }


def enforce(require_coverage: bool = False) -> None:
    """D7.1 gate: raise EgressUnhardened unless the filter is live and
    scoping is possible. No-op in permissive mode (explicit opt-out).

    `require_coverage=True` (Camoufox): the *gateway process itself* must sit
    inside the scoped cgroup — Camoufox spawns its own children and cannot be
    wrapped, so coverage is mandatory. For opencli ops the child is wrapped
    in a transient scope instead (`run_opencli`), so coverage is optional.
    """
    if HARDEN != "required":
        return
    if not table_installed():
        raise EgressUnhardened()
    if not systemd_run_available():
        raise EgressUnhardened()
    if require_coverage:
        state = _load_state()
        cg = current_cgroup()
        if not (cg and state.get("cgroup_path")
                and cg.rstrip("/") == state["cgroup_path"].rstrip("/")):
            raise EgressUnhardened()


def _scope_cgroup_path() -> str | None:
    """cgroup2 path of the transient scope `run_opencli` wraps children in.

    The wrapper uses the FIXED unit name `ks-egress`; where the scope lands
    depends on the caller's context (a shell's scope lands under app.slice;
    a unit's scope under that unit's slice), so install() must derive it by
    launching a probe scope from ITS OWN context, reading the cgroup, and
    letting it expire. The rules then match exactly what the wrapper creates
    from the same context (live-verified 2026-08-25).
    """
    systemd_run = shutil.which("systemd-run") or "systemd-run"
    systemctl = shutil.which("systemctl") or "systemctl"
    probe = subprocess.Popen(  # noqa: S603 — operator-triggered hardening probe
        [systemd_run, "--user", "--scope", "--collect", "--unit", "ks-egress",
         "--", "sleep", "5"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(0.7)  # let systemd create the scope and move the process
        r = subprocess.run(  # noqa: S603 — operator-triggered hardening probe
            [systemctl, "--user", "show", "ks-egress.scope",
             "-p", "ControlGroup", "--value"],
            capture_output=True, text=True, timeout=5)
        path = (r.stdout or "").strip()
        return path if path.startswith("/") else None
    finally:
        probe.wait(timeout=6)


def _unit_cgroup_path(unit: str) -> str | None:
    """cgroup2 path of a running user unit (e.g. `kortex-search@8765.service`).

    Used by the companion loader (`kortex-search-harden.service`): the rules
    must target the gateway unit's own cgroup (browser children inherit it),
    which only exists while the unit runs — so the loader runs After= it.
    """
    systemctl = shutil.which("systemctl") or "systemctl"
    r = subprocess.run(  # noqa: S603 — operator-triggered hardening probe
        [systemctl, "--user", "show", unit, "-p", "ControlGroup", "--value"],
        capture_output=True, text=True, timeout=5)
    path = (r.stdout or "").strip()
    return path if path.startswith("/") else None


def install(*, sudo: bool = False, dry_run: bool = False,
            for_unit: str | None = None) -> dict:
    """Idempotent install: derive the target cgroup, write the nft ruleset,
    load it, save state. Refuses (reports, never crashes) when nft or
    cgroupv2 is absent. `--sudo` runs the nft load with elevation; without
    sudo, the ruleset is written to a file for the operator to load
    (`nft -f`), and state marks it pending.

    Target derivation (live-verified 2026-08-25):
      * default: a probe of the `ks-egress` transient scope — the one
        `run_opencli` wraps browser children into (ad-hoc deployment; the
        gateway itself never sits under the strict cgroup, so its loopback
        stays open);
      * `for_unit`: the cgroup of a running user unit — used by the companion
        loader for the systemd deployment (children inherit the unit cgroup;
        the unit's loopback is exempt from the floor by design).
    """
    if _nft() is None:
        return {"ok": False, "error": "nft not on PATH — cannot harden"}
    if not cgroupv2_mounted():
        return {"ok": False, "error": "cgroupv2 not mounted at /sys/fs/cgroup"}
    if for_unit:
        cg = _unit_cgroup_path(for_unit)
        if not cg:
            return {"ok": False,
                    "error": f"unit {for_unit!r} not running — cannot derive "
                             "its cgroup (the loader must run After= it)"}
    else:
        cg = _scope_cgroup_path()
        if not cg:
            return {"ok": False,
                    "error": "cannot derive the ks-egress scope cgroup (is the "
                             "user systemd manager running?)"}
    rules = build_rules(cg)
    if dry_run:
        return {"ok": True, "dry_run": True, "cgroup_path": cg, "rules": rules}
    rules_path = RULES_PATH
    try:
        rules_path.parent.mkdir(parents=True, exist_ok=True)
        rules_path.write_text(rules, encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "error": f"cannot write rules file: {exc}"}
    if sudo or HARDEN_SUDO or os.geteuid() == 0:
        code, err = _run_nft(["-f", str(rules_path)])
        if code != 0:
            return {"ok": False, "error": f"nft -f failed: {err or code}"}
        _save_state({"cgroup_path": cg, "installed_at": int(time.time())})
        return {"ok": True, "cgroup_path": cg, "rules_file": str(rules_path)}
    logger.info("harden: rules written to %s — load with 'sudo nft -f %s'",
                rules_path, rules_path)
    _save_state({"cgroup_path": cg, "pending_load": str(rules_path)})
    return {"ok": True, "pending_load": str(rules_path),
            "cgroup_path": cg,
            "note": "rules written; load with 'sudo nft -f' or re-run with --sudo"}


def uninstall() -> dict:
    code, err = _run_nft(["delete", "table", *NFT_TABLE.split()])
    if code == 0:
        with contextlib.suppress(OSError):
            STATE_PATH.unlink()
        return {"ok": True}
    return {"ok": False, "error": f"nft delete failed: {err or code}"}
